In [1]:
import numpy as np

# GENERADORES

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1, 10, 2, dtype="float")

array([1., 3., 5., 7., 9.])

In [8]:
lista = np.arange(10)

# ACCESO

In [21]:
lista

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
lista[0:4]

array([0, 1, 2, 3])

In [26]:
lista[4]

4

# OPERACIONES

In [31]:
lista = np.arange(0,10, 2)
lista_2 = np.arange(10,60, 10)

In [38]:
lista

array([0, 2, 4, 6, 8])

In [32]:
lista + lista_2

array([10, 22, 34, 46, 58])

In [34]:
lista / lista_2

array([0.        , 0.1       , 0.13333333, 0.15      , 0.16      ])

In [35]:
lista **2

array([ 0,  4, 16, 36, 64])

In [27]:
lista / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [42]:
lista = np.arange(0,100)
lista[lista % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])